Add support for pre-stdout supporting dbpatch and tableversion loaders

diff --git a/scripts/linz-bde-schema-load.in b/scripts/linz-bde-schema-load.in
--- a/scripts/linz-bde-schema-load.in
+++ b/scripts/linz-bde-schema-load.in
@@ -47,8 +47,7 @@ fi
 
 export PGDATABASE=$DB_NAME
 
-
-# Enable dbpatch
+# Configure environment for dbpatch-loader
 PGBIN=`pg_config --bindir 2> /dev/null`
 if test -n "$PGBIN"; then
     PATH=$PATH:$PGBIN
@@ -61,41 +60,82 @@ else
     done
 fi
 
-die()
+rollback()
 {
     echo "ROLLBACK;"
     exit 1
 }
 
+# Find dbpatch-loader
+DBPATCH_LOADER=dbpatch-loader
+which $DBPATCH_LOADER > /dev/null || {
+    echo "$0 depends on $DBPATCH_LOADER, which cannot be found in current PATH." >&2
+    echo "Did you install dbpatch ? (1.2.0 or later needed)" >&2
+    exit 1
+}
+
+# Check if dbpatch-loader supports stdout
+dbpatch-loader -  > /dev/null &&
+    DBPATCH_SUPPORTS_STDOUT=yes ||
+    DBPATCH_SUPPORTS_STDOUT=no
+
+if test $PGDATABASE = "-" -a $DBPATCH_SUPPORTS_STDOUT != yes; then
+    echo "ERROR: dbpatch-loader does not support stdout mode, cannot proceed." >&2
+    exit 1
+fi
+
+DBPATCH_OPTS=
+if test "${EXTENSION_MODE}" = "off"; then
+    DBPATCH_OPTS="--no-extension"
+fi
+
+if test $DBPATCH_SUPPORTS_STDOUT != yes; then
+    echo "WARNING: dbpatch-loader does not support stdout mode, working in non-transactional mode" >&2
+    ${DBPATCH_LOADER} ${DBPATCH_OPTS} ${PGDATABASE} _patches || exit 1
+fi
+
+
+# Find table_version-loader
+TABLEVERSION_LOADER=table_version-loader
+which $TABLEVERSION_LOADER > /dev/null || {
+    echo "$0 depends on $TABLEVERSION_LOADER, which cannot be found in current PATH." >&2
+    echo "Did you install table_version ? (1.4.0 or later needed)" >&2
+    exit 1
+}
+
+# Check if table_version-loader supports stdout
+table_version-loader -  > /dev/null &&
+    TABLEVERSION_SUPPORTS_STDOUT=yes ||
+    TABLEVERSION_SUPPORTS_STDOUT=no
+
+if test $PGDATABASE = "-" -a $TABLEVERSION_SUPPORTS_STDOUT != yes; then
+    echo "ERROR: table_version-loader does not support stdout mode, cannot proceed" >&2
+    exit 1
+fi
+
+TABLEVERSION_OPTS=
+if test "${EXTENSION_MODE}" = "off"; then
+    TABLEVERSION_OPTS="--no-extension"
+fi
+
+if test "${ADD_REVISIONS}" = "yes" -a $TABLEVERSION_SUPPORTS_STDOUT != yes; then
+    echo "WARNING: table_version-loader does not support stdout mode, working in non-transactional mode" >&2
+    ${TABLEVERSION_LOADER} ${TABLEVERSION_OPTS} ${PGDATABASE} || exit 1
+fi
+
+
+
 {
 
 
-LOADER=dbpatch-loader
-which $LOADER > /dev/null || {
-    echo "$0 depends on $LOADER, which cannot be found in current PATH." >&2
-    echo "Did you install dbpatch ? (1.2.0 or later needed)" >&2
-    die
-}
 
-OPTS=
-if test "${EXTENSION_MODE}" = "off"; then
-    OPTS="--no-extension"
+if test $DBPATCH_SUPPORTS_STDOUT = yes; then
+    ${DBPATCH_LOADER} ${DBPATCH_OPTS} - _patches || rollback
 fi
-${LOADER} ${OPTS} $PGDATABASE _patches || die
 
 # Enable table_version if needed
-if test "${ADD_REVISIONS}" = "yes"; then
-    LOADER=table_version-loader
-    which $LOADER > /dev/null || {
-        echo "$0 depends on $LOADER, which cannot be found in current PATH." >&2
-        echo "Did you install table_version ? (1.4.0 or later needed)" >&2
-        die
-    }
-    OPTS=
-    if test "${EXTENSION_MODE}" = "off"; then
-        OPTS="--no-extension"
-    fi
-    ${LOADER} ${OPTS} $PGDATABASE || die
+if test "${ADD_REVISIONS}" = "yes" -a $TABLEVERSION_SUPPORTS_STDOUT = yes; then
+    ${TABLEVERSION_LOADER} ${TABLEVERSION_OPTS} - || rollback
 fi
 
 cat << EOF
@@ -109,12 +149,12 @@ for file in ${SCRIPTSDIR}/*.sql; do
     then
         continue
     fi
-    cat ${file} || die
+    cat ${file} || rollback
 done
 
 if test "${ADD_REVISIONS}" = "yes"; then
     file=${SCRIPTSDIR}/versioning/01-version_tables.sql
-    cat ${file} || die
+    cat ${file} || rollback
 fi
 
 echo "COMMIT;"
